version: '3.7'
networks:
    default:
        external:
            name: ws_bridge

        
services:
    web:
        build: .
        command: python app.py
        ports:
            - "5005:5005"
        volumes:
            - .:/service
        container_name: comp_parts